/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubmissionIndexRouteImport } from './routes/submission/index'
import { Route as RecentsIndexRouteImport } from './routes/recents/index'
import { Route as OmsIndexRouteImport } from './routes/oms/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionIndexRoute = SubmissionIndexRouteImport.update({
  id: '/submission/',
  path: '/submission/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentsIndexRoute = RecentsIndexRouteImport.update({
  id: '/recents/',
  path: '/recents/',
  getParentRoute: () => rootRouteImport,
} as any)
const OmsIndexRoute = OmsIndexRouteImport.update({
  id: '/oms/',
  path: '/oms/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oms': typeof OmsIndexRoute
  '/recents': typeof RecentsIndexRoute
  '/submission': typeof SubmissionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oms': typeof OmsIndexRoute
  '/recents': typeof RecentsIndexRoute
  '/submission': typeof SubmissionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oms/': typeof OmsIndexRoute
  '/recents/': typeof RecentsIndexRoute
  '/submission/': typeof SubmissionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oms' | '/recents' | '/submission'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oms' | '/recents' | '/submission'
  id: '__root__' | '/' | '/oms/' | '/recents/' | '/submission/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OmsIndexRoute: typeof OmsIndexRoute
  RecentsIndexRoute: typeof RecentsIndexRoute
  SubmissionIndexRoute: typeof SubmissionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission/': {
      id: '/submission/'
      path: '/submission'
      fullPath: '/submission'
      preLoaderRoute: typeof SubmissionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recents/': {
      id: '/recents/'
      path: '/recents'
      fullPath: '/recents'
      preLoaderRoute: typeof RecentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oms/': {
      id: '/oms/'
      path: '/oms'
      fullPath: '/oms'
      preLoaderRoute: typeof OmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OmsIndexRoute: OmsIndexRoute,
  RecentsIndexRoute: RecentsIndexRoute,
  SubmissionIndexRoute: SubmissionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
